INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'exclude-from-search', 'exclude-from-search', 0),
(7, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(8, 'featured', 'featured', 0),
(9, 'outofstock', 'outofstock', 0),
(10, 'rated-1', 'rated-1', 0),
(11, 'rated-2', 'rated-2', 0),
(12, 'rated-3', 'rated-3', 0),
(13, 'rated-4', 'rated-4', 0),
(14, 'rated-5', 'rated-5', 0),
(15, 'Uncategorized', 'uncategorized', 0),
(16, 'Best value', 'best-value', 0),
(17, 'Boutique', 'boutique', 0),
(18, 'Budget', 'budget', 0),
(19, 'Business', 'business', 0),
(20, 'Charming', 'charming', 0),
(21, 'Classic', 'classic', 0),
(22, 'Green', 'green', 0),
(23, 'Luxury', 'luxury', 0),
(24, 'Mid-range', 'mid-range', 0),
(25, 'Party', 'party', 0),
(26, 'Quaint', 'quaint', 0),
(27, 'Quite', 'quite', 0),
(28, 'Romantic', 'romantic', 0),
(29, 'Standard', 'standard', 0),
(30, 'Trendy', 'trendy', 0),
(31, 'Air Conditioning', 'air-conditioning', 0),
(32, 'Airport Transport', 'airport-transport', 0),
(33, 'Fitness Center', 'fitness-center', 0),
(34, 'Flat Tv', 'flat-tv', 0),
(35, 'Heater', 'heater', 0),
(36, 'Internet – Wifi', 'internet-wifi', 0),
(37, 'Parking', 'parking', 0),
(38, 'Pool', 'pool', 0),
(39, 'Restaurant', 'restaurant', 0),
(40, 'Smoking Room', 'smoking-room', 0),
(41, 'Spa &amp; Sauna', 'spa-sauna', 0),
(42, 'Washer &amp; Dryer', 'washer-dryer', 0),
(43, 'Air Conditioning', 'air-conditioning', 0),
(44, 'Flat Screen TV', 'flat-screen-tv', 0),
(45, 'Hair dryer', 'bathtub', 0),
(46, 'Hot water', 'terrace', 0),
(47, 'Kitchen', 'patio', 0),
(48, 'Shampoo', 'soundproof', 0),
(49, 'Wifi', 'mini-bar', 0),
(50, 'Bathroom robe', 'bathroom-robe', 0),
(51, 'Bathtub', 'bathroom', 0),
(52, 'Cart food', 'cart-food', 0),
(53, 'Suitcase key', 'suitcase-key', 0),
(54, 'Towels', 'pool', 0),
(55, 'traveler', 'traveler', 0),
(56, 'page', 'page', 0),
(57, 'TRAVEL', 'travel', 0),
(58, 'STAYS', 'stays', 0),
(59, 'HOTEL', 'hotel', 0),
(60, 'BOOKING', 'booking', 0),
(61, 'Main Menu', 'main-menu', 0),
(62, 'Family Suite', 'family-suite', 0),
(63, 'Deluxe', 'deluxe', 0),
(64, 'Normal', 'normal', 0),
(65, 'Queen Room', 'queen-room', 0),
(66, 'Standard Double-Double Room', 'standard-double-double-room', 0),
(67, 'Standard Room', 'standard-room', 0),
(68, 'Content', 'content', 0),
(69, 'SEO', 'seo', 0),
(70, 'Website', 'website', 0),
(71, 'Tools', 'tools', 0),
(72, 'Promotion', 'promotion', 0),
(73, 'Offers', 'offers', 0),
(74, 'Social media', 'social-media', 0),
(75, 'Traffic', 'traffic', 0),
(76, 'post-format-video', 'post-format-video', 0),
(77, 'section', 'section', 0),
(78, 'post-format-gallery', 'post-format-gallery', 0);