INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'exclude-from-search', 'exclude-from-search', 0),
(7, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(8, 'featured', 'featured', 0),
(9, 'outofstock', 'outofstock', 0),
(10, 'rated-1', 'rated-1', 0),
(11, 'rated-2', 'rated-2', 0),
(12, 'rated-3', 'rated-3', 0),
(13, 'rated-4', 'rated-4', 0),
(14, 'rated-5', 'rated-5', 0),
(15, 'Uncategorized', 'uncategorized', 0),
(16, 'Best value', 'best-value', 0),
(17, 'Boutique', 'boutique', 0),
(18, 'Budget', 'budget', 0),
(19, 'Business', 'business', 0),
(20, 'Charming', 'charming', 0),
(21, 'Classic', 'classic', 0),
(22, 'Green', 'green', 0),
(23, 'Luxury', 'luxury', 0),
(24, 'Mid-range', 'mid-range', 0),
(25, 'Party', 'party', 0),
(26, 'Quaint', 'quaint', 0),
(27, 'Quite', 'quite', 0),
(28, 'Romantic', 'romantic', 0),
(29, 'Standard', 'standard', 0),
(30, 'Trendy', 'trendy', 0),
(31, 'Air Conditioning', 'air-conditioning', 0),
(32, 'Airport Transport', 'airport-transport', 0),
(33, 'Fitness Center', 'fitness-center', 0),
(34, 'Flat Tv', 'flat-tv', 0),
(35, 'Heater', 'heater', 0),
(36, 'Internet – Wifi', 'internet-wifi', 0),
(37, 'Parking', 'parking', 0),
(38, 'Pool', 'pool', 0),
(39, 'Restaurant', 'restaurant', 0),
(40, 'Smoking Room', 'smoking-room', 0),
(41, 'Spa &amp; Sauna', 'spa-sauna', 0),
(42, 'Washer &amp; Dryer', 'washer-dryer', 0),
(43, 'Air Conditioning', 'air-conditioning', 0),
(44, 'Flat Screen TV', 'flat-screen-tv', 0),
(45, 'Hair dryer', 'bathtub', 0),
(46, 'Hot water', 'terrace', 0),
(47, 'Kitchen', 'patio', 0),
(48, 'Shampoo', 'soundproof', 0),
(49, 'Wifi', 'mini-bar', 0),
(50, 'Bathroom robe', 'bathroom-robe', 0),
(51, 'Bathtub', 'bathroom', 0),
(52, 'Cart food', 'cart-food', 0),
(53, 'Suitcase key', 'suitcase-key', 0),
(54, 'Towels', 'pool', 0),
(55, 'traveler', 'traveler', 0),
(56, 'page', 'page', 0),
(57, 'TRAVEL', 'travel', 0),
(58, 'STAYS', 'stays', 0),
(59, 'HOTEL', 'hotel', 0),
(60, 'BOOKING', 'booking', 0),
(61, 'Main Menu', 'main-menu', 0),
(62, 'Family Suite', 'family-suite', 0),
(63, 'Deluxe', 'deluxe', 0),
(64, 'Normal', 'normal', 0),
(65, 'Queen Room', 'queen-room', 0),
(66, 'Standard Double-Double Room', 'standard-double-double-room', 0),
(67, 'Standard Room', 'standard-room', 0),
(68, 'Content', 'content', 0),
(69, 'SEO', 'seo', 0),
(70, 'Website', 'website', 0),
(71, 'Tools', 'tools', 0),
(72, 'Promotion', 'promotion', 0),
(73, 'Offers', 'offers', 0),
(74, 'Social media', 'social-media', 0),
(75, 'Traffic', 'traffic', 0),
(76, 'post-format-video', 'post-format-video', 0),
(77, 'section', 'section', 0),
(78, 'City trips', 'city-trips', 0),
(79, 'Ecotourism', 'ecotourism', 0),
(80, 'Escorted Tour', 'escorted-tour', 0),
(81, 'Group Tour', 'group-tour', 0),
(82, 'Hosted tours', 'hosted-tours', 0),
(83, 'Ligula', 'ligula', 0),
(84, 'English', 'english', 0),
(85, 'Espanol', 'espanol', 0),
(86, 'Francais', 'francais', 0),
(87, 'Japanese', 'japanese', 0),
(88, 'Vietnamese', 'vietnamese', 0),
(89, '0 – 3 hours', '0-3-hours', 0),
(90, '3 – 5 hours', '3-5-hours', 0),
(91, '5 – 7 hours', '5-7-hours', 0),
(92, 'Fullday (+7hours)', 'fullday', 0),
(93, 'Multi day', 'multi-day', 0),
(94, 'Convertibles', 'convertibles', 0),
(95, 'Coupes', 'coupes', 0),
(96, 'Hatchbacks', 'hatchbacks', 0),
(97, 'Minivans', 'minivans', 0),
(98, 'Sedan', 'sedan', 0),
(99, 'SUVs', 'suvs', 0),
(100, 'Trucks', 'trucks', 0),
(101, 'Wagons', 'wagons', 0),
(102, 'Airbag', 'airbag', 0),
(103, 'FM Radio', 'fm-radio', 0),
(104, 'Power Windows', 'power-windows', 0),
(105, 'Sensor', 'sensor', 0),
(106, 'Speed Km', 'speed-km', 0),
(107, 'Steering Wheel', 'steering-wheel', 0),
(108, 'Audi', 'audi', 0),
(109, 'A1', 'a1', 0),
(110, 'A2', 'a2', 0),
(111, 'A3', 'a3', 0),
(112, 'Honda', 'honda', 0),
(113, 'City', 'city', 0),
(114, 'Mitsubishi', 'mitsubishi', 0),
(115, 'Outlander', 'outlander', 0),
(116, 'Air Conditioning', 'air-conditioning', 0),
(117, 'Flat Tv', 'tv', 0),
(118, 'Heater', 'heater', 0),
(119, 'Internet – Wifi', 'wi-fi-internet-2', 0),
(120, 'Pool', 'pool', 0),
(121, 'Washer &amp; Dryer', 'parking', 0),
(122, 'Elder Access', 'elder-access', 0),
(123, 'For Children', 'for-children', 0),
(124, 'No Smoking', 'smoking-allowed', 0),
(125, 'Pet Allowed', 'pet-allowed', 0),
(126, 'Wheelchair Access', 'wheelchair-access', 0),
(127, 'Apartment', 'apartment', 0),
(128, 'Condo', 'condo', 0),
(129, 'Duplex House', 'duplex-house', 0),
(130, 'House', 'house', 0),
(131, 'Studio', 'studio', 0),
(132, 'Townhome', 'townhome', 0),
(133, 'English', 'english', 0),
(134, 'Espanol', 'espanol', 0),
(135, 'Francais', 'francais', 0),
(136, 'Japanese', 'japanese', 0),
(137, 'Vietnamese', 'vietnamese', 0),
(138, 'Food &amp; Nightlife', 'food-nightlife', 0),
(139, 'Ourdoors', 'ourdoors', 0),
(140, 'Sightseeing Tours', 'sightseeing-tours', 0),
(141, 'Workshops', 'workshops-classes', 0),
(142, 'post-format-gallery', 'post-format-gallery', 0);