INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'exclude-from-search', 'exclude-from-search', 0),
(7, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(8, 'featured', 'featured', 0),
(9, 'outofstock', 'outofstock', 0),
(10, 'rated-1', 'rated-1', 0),
(11, 'rated-2', 'rated-2', 0),
(12, 'rated-3', 'rated-3', 0),
(13, 'rated-4', 'rated-4', 0),
(14, 'rated-5', 'rated-5', 0),
(15, 'Uncategorized', 'uncategorized', 0),
(16, 'Business', 'business', 0),
(17, 'Charming', 'charming', 0),
(18, 'Classic', 'classic', 0),
(19, 'Green', 'green', 0),
(20, 'Luxury', 'luxury', 0),
(21, 'Quaint', 'quaint', 0),
(22, 'Quite', 'quite', 0),
(23, 'Romantic', 'romantic', 0),
(24, 'Standard', 'standard', 0),
(25, 'Mid-range', 'mid-range', 0),
(26, 'Party', 'party', 0),
(27, 'Best value', 'best-value', 0),
(28, 'Boutique', 'boutique', 0),
(29, 'Budget', 'budget', 0),
(30, 'Trendy', 'trendy', 0),
(31, 'art galleries', 'art-galleries', 0),
(32, 'communities', 'communities', 0),
(33, 'Ethnic enclave', 'ethnic-enclave', 0),
(34, 'forests Museums', 'forests-museums', 0),
(35, 'Gallery', 'post-format-gallery', 0),
(36, 'Mountains', 'mountains', 0),
(37, 'Cultural events', 'cultural-events', 0),
(38, 'National parks', 'national-parks', 0),
(39, 'Natural beauty beaches', 'natural-beauty-beaches', 0),
(40, 'Quote', 'post-format-quote', 0),
(41, 'Theme parks', 'theme-parks', 0),
(42, 'Top News', 'top-news', 0),
(43, 'Traditional tourist', 'traditional-tourist', 0),
(44, 'Mountains', 'mountains', 0),
(46, 'Link', 'post-format-link', 0),
(47, 'Beauty beaches', 'beauty-beaches', 0),
(48, 'Parks and Carnivals', 'parks-and-carnivals', 0),
(49, 'Video', 'post-format-video', 0),
(50, 'Museums', 'museums', 0),
(51, 'Audio', 'post-format-audio', 0),
(52, 'National parks', 'national-parks', 0),
(53, 'Air Conditioning', 'air-conditioning', 0),
(54, 'Hair dryer', 'bathtub', 0),
(55, 'Flat Screen TV', 'flat-screen-tv', 0),
(56, 'Wifi', 'mini-bar', 0),
(57, 'Kitchen', 'patio', 0),
(58, 'Queen Room', 'queen-room', 0),
(59, 'Shampoo', 'soundproof', 0),
(60, 'Hot water', 'terrace', 0),
(61, 'Deluxe', 'deluxe', 0),
(62, 'Normal', 'normal', 0),
(63, 'Standard Double-Double Room', 'standard-double-double-room', 0),
(64, 'Standard Room', 'standard-room', 0),
(65, 'Family Suite', 'family-suite', 0),
(71, 'Hotel Menu', 'hotel-menu', 0),
(78, 'Airport Transport', 'airport-transport', 0),
(80, 'Air Conditioning', 'air-conditioning', 0),
(82, 'Fitness Center', 'fitness-center', 0),
(83, 'Flat Tv', 'flat-tv', 0),
(84, 'Heater', 'heater', 0),
(85, 'Internet – Wifi', 'internet-wifi', 0),
(86, 'Parking', 'parking', 0),
(87, 'Pool', 'pool', 0),
(88, 'Restaurant', 'restaurant', 0),
(89, 'Smoking Room', 'smoking-room', 0),
(90, 'Spa &amp; Sauna', 'spa-sauna', 0),
(91, 'Washer &amp; Dryer', 'washer-dryer', 0),
(92, 'Towels', 'pool', 0),
(93, 'Bathtub', 'bathroom', 0),
(94, 'Bathroom robe', 'bathroom-robe', 0),
(95, 'Cart food', 'cart-food', 0),
(96, 'Suitcase key', 'suitcase-key', 0),
(97, 'Tiptoe', 'tiptoe', 0),
(98, 'Tulips', 'tulips', 0),
(99, 'Washington', 'washington', 0),
(100, 'Carnivals', 'carnivals', 0),
(101, 'National', 'national', 0),
(102, 'Parks', 'parks', 0),
(103, 'beaches', 'beaches', 0),
(104, 'Beauty', 'beauty', 0),
(105, 'Cultural', 'cultural', 0),
(106, 'Museums', 'museums', 0),
(107, 'Image', 'post-format-image', 0),
(108, 'Footer New', 'footer-new', 0),
(109, 'Footer New 2', 'footer-new-2', 0),
(110, 'Non classifié(e)', 'non-classifiee', 0),
(111, 'Sin categorizar', 'sin-categorizar', 0),
(112, 'page', 'page', 0),
(113, 'traveler', 'traveler', 0);